### ISSUE TITLE
No module named pyfakefs

### ISSUE THREAD

**Issue by tomjones1977** [sa7mon/miniprint#64]
Ubuntu 18.04 LTS, fresh install.

Cloned the repository, ran pip install, then python3 ./server.py

I get the following error:

```
Traceback (most recent call last):
  File "./server.py", line 26, in <module>
    from printer import Printer
  File "/home/dcs-admin/miniprint/printer.py", line 20, in <module>
    from pyfakefs import fake_filesystem
ModuleNotFoundError: No module named 'pyfakefs'

```

**Comment by sa7mon** [comment]
It appears `pyfakefs` is not in your pip install packages. Re-run `pip install -r requirements.txt` and try it again.

**Comment by tomjones1977** [comment]
Should have said - I checked that pyfakefs was installed and even tried installing it again.

**Comment by sa7mon** [comment]
I just cloned a fresh copy of the repo into a new Ubuntu 18.04 VM and it worked just fine. Can you post the output of `pip list`

**Comment by djhashh** [comment]
pip3 install -r requirements

**Comment by sa7mon** [comment]
Could you please post the output of running `pip list` and `pip3 list`

**Comment by tomjones1977** [comment]
apipkg (1.5)
asn1crypto (0.24.0)
atomicwrites (1.3.0)
attrs (19.1.0)
configparser (3.7.4)
contextlib2 (0.5.5)
cryptography (2.1.4)
enum34 (1.1.6)
execnet (1.6.1)
funcsigs (1.0.2)
idna (2.6)
importlib-metadata (0.19)
ipaddress (1.0.17)
keyring (10.6.0)
keyrings.alt (3.0)
more-itertools (5.0.0)
packaging (19.1)
pathlib2 (2.3.4)
pip (9.0.1)
pluggy (0.12.0)
py (1.8.0)
pycrypto (2.6.1)
pyfakefs (3.6)
pygobject (3.26.1)
pyparsing (2.4.2)
pytest (4.6.5)
pytest-forked (1.0.2)
pytest-xdist (1.29.0)
pyxdg (0.25)
scandir (1.10.0)
SecretStorage (2.3.1)
setuptools (39.0.1)
six (1.11.0)
wcwidth (0.1.7)
wheel (0.30.0)
zipp (0.5.2)

**Comment by tomjones1977** [comment]
Fix found:
```
apt install python3-pip
pip3 install -r requirements.txt
python3 ./server.py
```
